### ISSUE TITLE
Parsing error 

### ISSUE THREAD

**Issue by katebygrace** [CircleCI-Public/slack-orb#307] opened 2021-11-10 23:58 UTC
## What happened:

Cannot parse json files. 

If we pass in our json template into the CI in the "custom" field, it works fine, but exporting it as a variable does not. 

## Expected behavior:

We need to be able to keep these jsons as files because we use them in a lot of places. 

## Additional Information:

See the stavvy org's stavvy-orb CI runs. They do not work. 

Posting Status
Checking For JQ + CURL: Debian
parse error: Invalid numeric literal at line 1, column 2
parse error: Invalid numeric literal at line 1, column 2

I've tried every single possible way I can come up with to export these files. None of them work.

**Comment by HennaAbbas** [comment] 2022-01-06 23:02
@katebygrace Thanks for reporting this issue. Can you please share a build link to where you are seeing this error so I can get a better understanding of the issue.

**Comment by EricRibeiro** [comment] 2022-01-17 16:09
It might be a duplicate of #219. If so, [Kyle's comment](https://github.com/CircleCI-Public/slack-orb/issues/219#issuecomment-750366813) might help.

**Comment by EricRibeiro** [comment] 2022-01-20 19:40
Hi @katebygrace. If you are still experiencing this problem, please let us know by opening another issue with an example of your template.

Also, try taking a look at our [dynamic template wiki ](https://github.com/CircleCI-Public/slack-orb/issues/219#issuecomment-750366813)to learn the proper way of using environment variables with the slack orb.

**Closed by EricRibeiro** 2022-01-20 19:40 UTC
Labels: bug
