### ISSUE TITLE
Implement Dynamic Custom Templates processing

### ISSUE THREAD

**Issue by zumby** [CircleCI-Public/slack-orb#246] opened 2021-03-01 18:56 UTC
## Describe Request:

There is no way to **centrally manage custom templates** at the moment.

Users may want this hard:
- store custom templates in 1 place
- manage them only in that place only
- refer to templates (reuse) in many pipelines

Please implement something like **dynamic custom templates processing**

## Examples:

```
version: 2.1
orbs:
  slack: circleci/slack@4.3.0
executors:
  cimg-base:
    docker:
      - image: cimg/base:stable
    resource_class: small
workflows:
  version: 2.1
  WF1:
    jobs:
      - JOB1:
          filters:
            branches:
              only:
                - /tst-slack-notify/
          context:
            - SLACK
jobs:
  JOB1:
    executor: cimg-base
    steps:
      - run: echo 'hello'
      - slack/notify:
          event: pass
          channel: 'C0XXXXXXXFR'
          custom: $(curl -s https://raw.githubusercontent.com/CircleCI-Public/slack-orb/master/src/message_templates/basic_success_1.json)

```
If you try to use a template that is fetched, i.e by Curl, you'll get the error message:
Im no expert, but looks like it has something to do with how you process template with JQ and how the template is being passed to your script notify.sh

![image](https://user-images.githubusercontent.com/26290616/109544373-28217680-7ad0-11eb-8f1d-a60416ee9691.png)

**Comment by gmemstr** [comment] 2021-03-03 12:29
I assume this error is due to the way we `exec` the passed template to properly expand environment variables. While this is an interesting use case, we do typically recommend that shared templates use [contexts](https://circleci.com/docs/2.0/contexts/). The downside to this, of course, is that these can't be edited after the fact within CircleCI itself. I almost feel inclined to say we should add this, but I am curious if others will find it useful as well.

**Comment by KyleTryon** [comment] 2021-03-08 16:43
Hello @bzumby We have put together this guide on using contexts (as @gmemstr mentioned above) https://github.com/CircleCI-Public/slack-orb/wiki/Reuse-Custom-Templates

I believe this fits most of your needs, and contexts can also be updated via the API or CLI. I believe we could support this, but likely would require an additional parameter, something like `template_url`, I would like to try to limit the total number of parameters where possible. Could you tell us if you find this context solution to be satisfactory?

**Comment by bzumby** [comment] 2021-03-08 17:08
@KyleTryon  Honestly, using Contexts sounds even better to me. But the problem is that before you even created this guild, i already tried using raw JSON inside ENV_VAR of a Context and then referenced it in **custom** parameter of your orb. And that did not work - failed with similar error _"Invalid numeric literal ..."_ which is a template parse error i guess. 

Also, you're saying to use it like this
```
template: MY_SLACK_TEMPLATE
```
But at the same time, **template** is expected to be a string. So I'm not sure if this works as you describe. 
![image](https://user-images.githubusercontent.com/26290616/110354281-aafe8000-8040-11eb-86ff-c6eca02acc80.png)

Though, I of course trust you and really don't want to reproduce using Contexts once _again_ - if you say it's gonna work - then great. 

P.S.
I could not wait for your changes and had some time to play around with this based on your orb, and eventually implemented template usage from URL: https://github.com/bzumby/slack-notify-orb/blob/master/src/scripts/notify.sh#L22 
But probably we'll use your orb further if what you're saying is really working ;)

**Comment by KyleTryon** [comment] 2021-06-16 20:09
@zumby Is everything working for you now?

**Comment by EricRibeiro** [comment] 2022-01-13 14:31
@zumby, I hope our orb is working for you. I'll close this issue due to staleness.

I want to add that in the issue you mentioned in your comment (#219), the user was successful using [dynamic templates](https://github.com/CircleCI-Public/slack-orb/wiki/Dynamic-Templates). If you are still having problems, give them a shot and, if it still doesn't work, let us know!

**Closed by EricRibeiro** 2022-01-13 14:31 UTC
