### ISSUE TITLE
Error status with basic_success_1

### ISSUE THREAD

**Issue by garyhighlinebeta** [CircleCI-Public/slack-orb#346] opened 2022-04-12 01:28 UTC
## Orb version:
4.1

## What happened:
Jobs:
deploy-dev:

    working_directory: ~/server
    machine: true
    steps:
      # Clone code from GitHub
      - checkout
      - slack/notify:
          event: pass
          template: basic_success_1

But it gives the following error in CircleCI

Posting Status
Checking For JQ + CURL: Debian
Sending to Slack Channel: **************
{
  "ok": false,
  "error": "invalid_arguments"
}

**Comment by hv-rruiz** [comment] 2022-04-27 18:55
Upgrade the slack orb to the latest version: ```@4.9.3```.

The basic_success_1 template worked as intended in that version.

**Comment by KyleTryon** [comment] 2022-05-02 14:25
Closing, thank you @hv-rruiz

**Closed by KyleTryon** 2022-05-02 14:25 UTC
Labels: bug
