### ISSUE TITLE
Not possible to avoid running on branches

### ISSUE THREAD

**Issue by goetzc** [CircleCI-Public/slack-orb#415] opened 2023-06-21 21:44 UTC
## What happened:

I want to avoid sending the notification on any branch trigger, including the default `main` branch. Only want to send notifications on workflows triggered by tags. So I have set `branch_pattern` and `tag_pattern` to different values without success.

```yaml
branch_pattern: ''
# or
branch_pattern: ' '
# or
branch_pattern: '.'
# or
branch_pattern: '(?!)'
```

Or according to the README https://github.com/CircleCI-Public/slack-orb/blob/3e43e753919b007d681cb2a16b37cabe5a8eda83/README.md?plain=1#L61 

> Keep in mind that "branch_pattern" and "tag_pattern" are mutually exclusive.

but it seems outdated as it's not working with:

```yaml
tag_pattern: '.+'
``` 

Without any pattern (or using the `tag_pattern`) it send the notification. On any of the `branch_pattern` above, it fails with the following error: 

```
NO SLACK ALERT

Current reference "main" does not match any matching parameter
Current matching pattern: .

Exited with code exit status 1

CircleCI received exit code 1
```

![image](https://github.com/CircleCI-Public/slack-orb/assets/2220440/2d1a4d43-16cb-47d2-b33a-7fa07e44acff)
![image](https://github.com/CircleCI-Public/slack-orb/assets/2220440/7e7cdfd7-3adb-487b-be05-da98e31f00b6)

Which makes the whole job fail.

## Expected behavior:

I expect it to avoid sending the notification on any branch (including the default branch), and exiting cleanly with code 0, so the whole workflow/job passes.

## Additional Information:

I'm not sure if I'm missing something, as the normal job filters (`filters.tags.only`, `filters.branches.only` or `filters.branches.ignore`) work normally. Is there some special pattern to avoid sending the notification on any branch?

Thanks

**Comment by marboledacci** [comment] 2024-09-16 16:42
The development of the go version of the orb is on stand by for now. I'm checking this issue to see if there's a way you can implement it or if we need to do a change on the pattern logic.
For now, is it possible for your use case to use the normal job filters? More information [here](https://circleci.com/docs/configuration-reference/#jobfilters)

**Comment by marboledacci** [comment] 2024-09-16 19:17
@goetzc You explained two problems, the pattern not working and the exit 1.
The first, you are using login shell. That's the cause of the exit 1 error. This shouldn't happen in the last version of the orb, as it is using a default shell configuration.
The second I'm fixing in PR #459, this should be fixed in our next release.

**Comment by marboledacci** [comment] 2024-09-17 18:46
Version [4.14.0](https://circleci.com/developer/orbs/orb/circleci/slack?version=4.14.0) is solving the issue with tag pattern.

**Closed** 2024-10-04 14:36 UTC
Labels: bug
